---
env:
    es6: true
    node: true
    jest: true
extends:
    - "airbnb-base"
    - "prettier"
rules:
    quotes:
        - error
        - single
    import/no-dynamic-require:
        - off
    object-curly-spacing:
        - warn
