AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  restauranto-api

  Sample SAM Template for restauranto-api
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  Env:
    Type: String
    AllowedValues:
      - dev
      - staging
      - prod

Resources:
  ########################
  #
  # Lambda Functions
  #
  ########################
  PlacesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/places/
      Handler: index.handler
      Runtime: nodejs12.x
      Events:
        Places:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /places
            Method: get
      Layers:
        - !Ref UtilsLayer
      Environment:
        Variables:
          Env: !Ref Env

  ########################
  #
  # Layers
  #
  ########################
  UtilsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: Utils
      Description: Shared utilities for Lambdas
      ContentUri: src/layers
      CompatibleRuntimes:
        - nodejs12.x

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PlacesApi:
    Description: "API Gateway endpoint URL for Prod stage for Places endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/places/"
  PlacesFunction:
    Description: "Places Lambda Function ARN"
    Value: !GetAtt PlacesFunction.Arn
  PlacesFunctionIamRole:
    Description: "Implicit IAM Role created for Places function"
    Value: !GetAtt PlacesFunction.Arn
