AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  kickstarter-api

  Sample SAM Template for kickstarter-api
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  Env:
    Type: String
    AllowedValues:
      - dev
      - staging
      - prod

Resources:
  ########################
  #
  # Lambda Functions
  #
  ########################
  SampleFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/sample/
      Handler: index.handler
      Runtime: nodejs12.x
      Events:
        Places:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /sample
            Method: get
      Layers:
        - !Ref UtilsLayer
      Environment:
        Variables:
          Env: !Ref Env

  ########################
  #
  # Layers
  #
  ########################
  UtilsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: Utils
      Description: Shared utilities for Lambdas
      ContentUri: src/layers
      CompatibleRuntimes:
        - nodejs12.x

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SampleApi:
    Description: "API Gateway endpoint URL for Prod stage for Sample endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/sample/"
  SampleFunction:
    Description: "Sample Lambda Function ARN"
    Value: !GetAtt SampleFunction.Arn
  SampleFunctionIamRole:
    Description: "Implicit IAM Role created for Sample function"
    Value: !GetAtt SampleFunctionRole.Arn
