# This is a basic workflow to help you get started with Actions
name: Build & Deploy AWS SAM Prod Stack

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    pull_request:
        types: [closed]
        branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "deploy"
    deploy:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            ##########################
            # Checkout the code base #
            ##########################
            - name: Checkout Code
              uses: actions/checkout@v2

            ############
            # Use Node #
            ############
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'

            ########################
            # Install Dependencies #
            ########################
            - name: Install Dependencies
              run: npm install

            #############################
            # Setup AWS CLI Credentials #
            #############################
            - name: Configure AWS credentials from Prod account
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            #######################
            # Deploy with AWS SAM #
            #######################
            - name: Deploy with AWS SAM
              run: npm run deployProdCICD
